language: python

python:
  - 3.2
  - 3.3
  - 3.4

branches:
  only:
    - master
    - develop

install: pip install --quiet flake8 nose mock

script:
  - flake8 --ignore=E501,E910,F401 --max-complexity 14 jsonrpc
  - nosetests

after_script:
  - pip install --quiet coverage coveralls
  - coverage run -m nose
  - coverage report
  - coveralls
